# Docker compose file for local development mode
services:
  weaponsforge.sendemail-dev:
    container_name: weaponsforge-sendemail-dev
    image: weaponsforge/sendemail:dev
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./app:/opt/app
      - /opt/app/node_modules
    ports:
      - "9229:9229"     # VSCode debugger
      - "4173:4173"     # vitest --ui web server
      - "51204:51204"   # vitest ui reports preview web server
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
