name: Run Unit/Integration Tests

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test-app:
    name: Test App
    runs-on: ubuntu-latest
    env:
      GOOGLE_USER_EMAIL: ${{ secrets.GOOGLE_USER_EMAIL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Use NodeJS v22.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Test
        run: |
          cd app
          npm test
